//GENERAL DEFINES
#define SUCCESS 1
#define FAILURE 0
#define MAX_ACCESSCODE_DIGITS 4
#define MAX_LINESIZE 5000
#define MAX_SKILL	10
#define MAX_PSYCH	6
#define MAX_SPECIALIZATION	3
#define MAX_DESC_SIZE 1000
#define MAX_WEAPON_SOUNDS 6
#define MAX_SHORTNAME_CHARS 20
#define MAX_NAME_CHARS 60
#define MAX_PLAYER_WEIGHT 40.00
#define ATOMIC_BOMB_WEIGHT 10.50
#define ROUND_WEIGHT .02
#define MAX_RESPONSE_CHARS 40
#define CODENAMELENGTH 40
#define MAX_GREEK_LETTERS 20
#define MAX_GREEK_CHARACTERS 24
#define RET_EXIT	-1
#define RET_OK	0
#define MAX_HEALTH 100
#define VAN_NIGHTMODE_SOUND	"sounds\\modifiers\\lasersight.wav"
#define VAN_DOORBEEP_SOUND	"sounds\\common\\vannr.wav"
#define VAN_DOOROPEN_SOUND	"sounds\\common\\vandoor.wav"
#define PICKUP_WEAPON_SOUND	"sounds\\common\\pickupweapon.wav"
#define MAX_VIEW_RANGE	120
#define MAX_PLAYER_THROW_OFF		7.0
#define PLAYER_THROW_SPECIAL_ACCURACY_BONUS	2.0
#define MAX_PLAYER_THROW_DISTANCE	40
#define MAX_PLAYER_THROW_WEAP_FALLOFF_WEIGHT	10.0
#define MAX_PLAYER_THROW_WEAP_FALLOFF_PSYCH		20.0
#define MAX_PLAYER_THROW_WEIGHT		15.0



//DIALOG BOX DEFINES
#define DB_SMALL	0
#define DB_MEDIUM	1
#define DB_LARGE	2
#define DB_NOBORDER	0
#define DB_SINGLEBORDER	1
#define DB_DOUBLEBORDER 2
#define DB_BLOCKBORDER	3

#define DB_SCHEME_EMERGENCYREDLINES	0
#define DB_SCHEME_BLUEANDYELLOW	1
#define DB_SCHEME_DIGITALGREENLINES	2
#define DB_SCHEME_REDANDYELLOW	3
#define DB_SCHEME_COOLBLUELINES 4
#define DB_SCHEME_MONOCHROMATIC 5

//MISSION TYPE DEFINES
#define MISSION_TYPE_TECHNOLOGYRETRIEVAL 0
#define MISSION_STRING_TECHNOLOGYRETRIEVAL "Technology Retrieval"
#define MISSION_TYPE_SURVEILLANCEDEVICEPLACEMENT	1
#define MISSION_STRING_SURVEILLANCEDEVICEPLACEMENT "Surveillance Device Placement"
#define MISSION_TYPE_ISR	2
#define MISSION_STRING_ISR "Interrogation Subject Retrieval"
#define MISSION_TYPE_ASSASSINATION	3
#define MISSION_STRING_ASSASSINATION "Target Shutdown"
#define MISSION_TYPE_NOTOCHORD	4
#define MISSION_STRING_NOTOCHORD "Agent NOTOCHORD"
#define MISSION_TYPE_RESCUE	5
#define MISSION_STRING_RESCUE "Agent Rescue"
#define MISSION_TYPE_CAUTERIZATION	6
#define MISSION_STRING_CAUTERIZATION "Complete Cauterization"
#define MISSION_TYPE_ESCAPE			7
#define MISSION_STRING_ESCAPE		"Compound Escape"

//MUSIC DEFINES
#define INTRO_SONG				0
#define CREDITS_SONG		1
#define TSSI_SONG				2
#define TRAINING_SONG		3
#define SARTU_SONG			4
#define MOBILIZE_SONG	5
#define INGRESS_SONG	6
#define STEALTH_SONG	7
#define DYNAMIC_SONG	8
#define INVENTORY_SONG	9
#define ELECTRONICS_SONG 10
#define SNIPING_SONG	11
#define HANDTOHAND_SONG	12
#define EGRESS_SONG	13
#define EXTRACTION_SONG	14
#define ATOMIC_SONG		15
#define CAPTIVITY_SONG 16
#define ESCAPE_SONG	17
#define POSTMISSION_SONG	18
#define ENDGAME_SONG		19


#define MUSICLISTFILE	"data\\songs.dat"
#define MAXSONGS 20

#define MUSICTHREADID		1

//MUSIC PROC DEFINES
#define MUSIC_STOP			2
#define MUSIC_PLAY			0
#define MUSIC_LOOP			1
#define MUSIC_INIT			3
#define MUSIC_TERMINATE		4

//SOUND MODE DEFINES
#define SOUND_MODE_SYNC			0
#define SOUND_MODE_ASYNC		1
#define SOUND_MODE_MIX			2

//SARTU DEFINES
#define DSAFIRSTNAMESFILE	"data\\dsanamea.dat"
#define DSALASTNAMESFILE	"data\\dsanameb.dat"
#define DSACODENAMESFILE	"data\\dsacname.dat"
#define TECHNOLOGYNAMESFILE	"data\\techs.dat"
#define MISSIONCODENAMESONEFILE	"data\\codebegin.dat"
#define MISSIONCODENAMESTWOFILE	"data\\codeend.dat"
#define TARGETFIRSTNAMESFILE "data\\dnamesa.dat"
#define TARGETLASTNAMESFILE "data\\dnamesb.dat"
#define TARGETEXTRADATAFILE "data\\dextra.dat"
#define GOGETEMONEFILE "data\\gg1.dat"
#define GOGETEMTWOFILE "data\\gg2.dat"
#define EMERGENCYGOGETEMONEFILE	"data\\gge1.dat"
#define EMERGENCYGOGETEMTWOFILE "data\\gge2.dat"
#define MIN_MAP_HEIGHT	50
#define MIN_MAP_WIDTH	50
#define MAX_MAP_HEIGHT	300
#define MAX_MAP_WIDTH	300
#define MIN_GUARD_DENSITY	.00175
#define MAX_GUARD_DENSITY	.01
#define GUARD_DENSITY_SCALE_FACTOR	1000000
#define MIN_ARMORY_DENSITY	.00152
#define MAX_ARMORY_DENSITY	.006
#define ARMORY_DENSITY_SCALE_FACTOR	1000000
#define MIN_VEHICLE_DENSITY	.00152
#define MAX_VEHICLE_DENSITY	.006
#define VEHICLE_DENSITY_SCALE_FACTOR	1000000
#define DENSITY_SCALEDOWN_FACTOR	20
#define SARTU_SCREEN_LOGINX	9
#define SARTU_SCREEN_LOGINY	1
#define SARTU_SCREEN_BRIEFORIGINX	1
#define SARTU_SCREEN_BRIEFORIGINY	4
#define SARTU_SCREEN_BRIEFHEIGHT	15
#define SARTU_SCREEN_BRIEFWIDTH	78
#define SARTU_SCREEN_CODEX	72
#define SARTU_SCREEN_CODEY	21
#define SARTU_KEYBOARD_SOUND	"sounds\\common\\keyboard.wav"


//ARMORY DEFINES
#define ARMORY_GIZMO_FILE		"data\\gizmos.dat"
#define ARMORY_LEFTBOXXORIGIN	0
#define ARMORY_LEFTBOXYORIGIN	0
#define ARMORY_RIGHTBOXXORIGIN	40
#define ARMORY_RIGHTBOXYORIGIN	0
#define ARMORY_TOPBOXESWIDTH	39
#define ARMORY_TOPBOXESHEIGHT	10
#define ARMORY_WEIGHTBOXXORIGIN	0
#define ARMORY_WEIGHTBOXYORIGIN	12
#define ARMORY_WEIGHTBOXWIDTH	80
#define ARMORY_WEIGHTBOXHEIGHT	0
#define ARMORY_DESCBOXXORIGIN	0
#define ARMORY_DESCBOXYORIGIN	15
#define ARMORY_DESCBOXWIDTH		80
#define ARMORY_DESCBOXHEIGHT	9
#define ARMORY_SOUND_SELECT		"sounds\\common\\weaponselect.wav"
#define ARMORY_SOUND_GETWEAPON	"sounds\\common\\weaponaccept.wav"
#define ARMORY_SOUND_REMOVEWEAPON	"sounds\\common\\weaponremove.wav"


//OPERATIVE STATUS DEFINES

#define OPERATIVE_STATUS_ACTIVE			0
#define OPERATIVE_STATUS_CYANIDED		1
#define OPERATIVE_STATUS_NOTOCHORDED	2
#define OPERATIVE_STATUS_RETIRED		3
#define OPERATIVE_STATUS_WHEREABOUTS_UNKNOWN	4
#define OPERATIVE_STATUS_DEADAFTERTORTURE	5

#define OPERATIVE_SEALED_FILE	1
#define OPERATIVE_OPEN_FILE	0

/*
#define  OPERATIVE_STATUS_OPCON 0
#define  OPERATIVE_STATUS_OPERATION 1
#define OPERATIVE_STATUS_CAPTURED 2
#define OPERATIVE_STATUS_DECEASED 3
#define OPERATIVE_STATUS_DT 4
#define OPERATIVE_STATUS_HT 5
#define OPERATIVE_STATUS_SILENT_WALL 6
#define OPERATIVE_ALIVE 1
#define OPERATIVE_DEAD 0

//OPERATIVE HISTORY DEFINES
#define HMATRIX_PREVIOUSEMPLOYMENT_MILITARY 0
#define HMATRIX_PREVIOUSEMPLOYMENT_CIA 1
#define HMATRIX_PREVIOUSEMPLOYMENT_NSA 2
#define HMATRIX_PREVIOUSEMPLOYMENT_DIA 3
#define HMATRIX_PREVIOUSEMPLOYMENT_ISS 4
	
#define HMATRIX_PREVIOUSSPECIALIZATION_ELECTRONICS 1
#define HMATRIX_PREVIOUSSPECIALIZATION_FIELDOPS 2
#define HMATRIX_PREVIOUSSPECIALIZATION_DARKOPS 3
#define HMATRIX_PREVIOUSSPECIALIZATION_TECH 4
*/
//WEAPON DEFINES
#define WEAP_ATT_TYPE_SHOOT 1
#define WEAP_ATT_TYPE_THROW 2
#define WEAP_ATT_TYPE_CUT 4
#define WEAP_ATT_TYPE_HIT 8
#define WEAP_ATT_TYPE_DRUG 16
#define WEAP_ATT_TYPE_SNIPE	32
#define MAX_ATTACK_VALUE 63

#define WEAP_SOUND_FIRE		0
#define WEAP_SOUND_THROW	1
#define WEAP_SOUND_SFIRE	1
#define WEAP_SOUND_HIT			2
#define WEAP_SOUND_DROP		3
#define WEAP_SOUND_RELOAD	4
#define WEAP_SOUND_BREAK	5
#define MAX_WEAP_SOUNDS		6
#define WEAPONSOUND_SHOOT	0
#define WEAPONSOUND_THROW	1
#define WEAPONSOUND_SILENCEDSHOOT	1
#define WEAPONSOUND_HIT				2
#define WEAPONSOUND_DROP		3
#define WEAPONSOUND_RELOAD		4
#define WEAPONSOUND_BREAK		5

#define WEAPONSOUND_DEFAULT_SHOOT	"sounds\\weapons\\pistol1.wav"
#define WEAPONSOUND_DEFAULT_THROW	"sounds\\weapons\\spistol1.wav"
#define WEAPONSOUND_DEFAULT_DROP		"sounds\\weapons\\gundrop2.wav"
#define WEAPONSOUND_DEFAULT_RELOAD	"sounds\\weapons\\reloadb.wav"
#define WEAPONSOUND_DEFAULT_HIT				"sounds\\hits\\hitwithweapon.wav"
#define WEAPONSOUND_DEFAULT_BREAK		"sounds\\weapons\\click.wav"
#define IMPACTSOUND_DEFAULT_BULLET			"sounds\\hits\\bullethit.wav"
#define IMPACTSOUND_DEFAULT_SHELL			"sounds\\hits\\shellhit.wav"
#define IMPACTSOUND_DEFAULT_EXPLOSIVE	"sounds\\hits\\explosivehit.wav"

#define MAX_WEAP_FILING_TYPES	8
#define WEAP_FILING_TYPE_NONE	0
#define WEAP_FILING_TYPE_NONE_S	"None"
#define WEAP_FILING_TYPE_MELEE		1
#define WEAP_FILING_TYPE_MELEE_S	"Close Range"
#define WEAP_FILING_TYPE_PISTOLS	2
#define WEAP_FILING_TYPE_PISTOLS_S	"Pistol"
#define WEAP_FILING_TYPE_SMGS		3
#define WEAP_FILING_TYPE_SMGS_S			"Sub-Machinegun"
#define WEAP_FILING_TYPE_RIFLES		4
#define WEAP_FILING_TYPE_RIFLES_S		"Rifle"
#define WEAP_FILING_TYPE_SHOTGUN	5
#define WEAP_FILING_TYPE_SHOTGUN_S	"Shotgun"
#define WEAP_FILING_TYPE_HEAVY		6
#define WEAP_FILING_TYPE_HEAVY_S		"Heavy"
#define WEAP_FILING_TYPE_SPECIAL	7
#define WEAP_FILING_TYPE_SPECIAL_S		"Special"

#define MAX_WEAP_CLASSES	5
#define WEAP_CLASS_NONE	0
#define WEAP_CLASS_NONE_S	"None"
#define WEAP_CLASS_A	1
#define WEAP_CLASS_A_S	"\"A\""
#define	WEAP_CLASS_B	2
#define WEAP_CLASS_B_S	"\"B\""
#define WEAP_CLASS_S	3
#define WEAP_CLASS_S_S	"\"S\""
#define WEAP_CLASS_X	4
#define WEAP_CLASS_X_S	"\"X\""

#define CYLINDER_CHAMBER_EMPTY 0
#define CYLINDER_CHAMBER_FULL 1
#define CYLINDER_CHAMBER_SHELLONLY -1

#define MAX_POISONS 3
#define POISON_NONE	0
#define POISON_CYANIDE	1
#define POISON_KETAMINE	2


#define WEAP_MAX_LOADTYPES		4
#define WEAP_LOADTYPE_NONE			0
#define WEAP_LOADTYPE_CLIP				1
#define WEAP_LOADTYPE_MAGAZINE	2
#define WEAP_LOADTYPE_CYLINDER		3

#define NOT_DSA_WEAPON 0
#define DSA_WEAPON 1

//AMMO DEFINES
#define AMMOTYPE_BULLET						0
#define AMMOTYPE_SHOTGUNSHELL	  1
#define AMMOTYPE_EXPLOSIVE				2
#define MAX_DEBUG_ROUNDS_AVAILABLE 50000
#define MAX_BASE_SHELLS		150
#define MAX_BASE_BULLETS	300
#define MAX_BASE_EXPLOSIVE	50
#define SUBTRACTCONSTANT_BULLETS	9
#define SUBTRACTCONSTANT_SHELLS		6
#define SUBTRACTCONSTANT_EXPLOSIVE	3
//EXPLOSIVE DEFINES
//--------INITIAL DAMAGE TYPES
#define EX_IDAMAGE_TYPE_NONE					0
#define EX_IDAMAGE_TYPE_CONCUSSION		1
#define EX_IDAMAGE_TYPE_PUNCTURE			2
#define EX_IDAMAGE_TYPE_FLASH					3
//---------LASTING DAMAGE TYPES
#define EX_LDAMAGE_TYPE_NONE					0
#define EX_LDAMAGE_TYPE_GAS						1
#define EX_LDAMAGE_TYPE_SMOKE				2
#define EX_LDAMAGE_TYPE_FIRE					3

//DRUG SYRINGE DEFINES
#define DRUG_STIMULANT 1
#define DRUG_ADRENALIN 2
#define DRUG_REMEDK 3
#define DRUG_ANTIDOTE 4
#define SYRINGE_ALPHA 0
#define SYRINGE_BETA 1
#define SYRINGE_GAMMA 2
#define MAX_SYRINGES 3
#define REMEDK_HEALTH_POINTS 35
#define SYRINGE_FILL_SOUND	"sounds\\gizmos\\syringeuse.wav"
#define SYRINGE_USE_SOUND	"sounds\\gizmos\\syringefill.wav"

#define NUMBERREPORT_SLEEP 200


//AGENT DEFINES
#define AGENT_RANK_FOR	0
#define AGENT_RANK_FO	1
#define AGENT_RANK_CO	2
#define AGENT_RANK_COS	3
#define AGENT_RANK_ECOS	4
#define AGENT_RANK_ECOSSPECONE	5
#define MAX_RANK	5

//STATUS SCREEN DEFINES
#define ST_IDWEAPON1 1 
#define ST_IDWEAPON2 2
#define ST_IDWEAPON3 3
#define ST_IDWEAPON4 4 
#define ST_IDWEAPON5 5
#define ST_IDWEAPON6 6
#define ST_IDGIZMO1 7
#define ST_IDGIZMO2 8
#define ST_IDGIZMO3 9
#define ST_IDSYRINGE1 10
#define ST_IDSYRINGE2 11
#define ST_IDSYRINGE3 12

#define ST_WEAPXCOORD 1
#define ST_WEAPYCOORD1 2
#define ST_WEAPYCOORD2 3
#define ST_WEAPYCOORD3 4
#define ST_WEAPYCOORD4 5
#define ST_WEAPYCOORD5 6
#define ST_WEAPYCOORD6 7
#define ST_WEAPYCOORD7 10
#define ST_WEAPYCOORD8 11
#define ST_WEAPYCOORD9 12

#define ST_SYRINGEXCOORD 48
#define ST_SYRINGEYCOORD1 16
#define ST_SYRINGEYCOORD2 17
#define ST_SYRINGEYCOORD3 18

#define ST_WEAPONSTITLEX 21
#define ST_WEAPONSTITLEY 1

#define ST_PLAYERSTATTITLEX 57
#define ST_PLAYERSTATTITLEY 1

#define ST_GIZMOSTITLEX 21
#define ST_GIZMOSTITLEY 9

#define ST_SYRINGETITLEX 56
#define ST_SYRINGETITLEY 14

#define ST_USEX 12
#define ST_USEY 21

#define ST_DROPX 29
#define ST_DROPY 21

#define ST_CHECKX 49
#define ST_CHECKY 21

#define ST_SELECTWEAPX 8
#define ST_SELECTWEAPY 22

#define ST_SELECTSTATUSX 43
#define ST_SELECTSTATUSY 22

#define ARROWCHAR 16

//SHOOTING DEFINES
#define SHOOTING_TGTPOS_OPEN	0
#define SHOOTING_TGTPOS_PARTIALCOVER	1
#define SHOOTING_TGTPOS_FULLCOVER	2

//SNIPING DEFINES
#define SNIPECODE_OVEROCULAR	-1
#define SNIPECODE_MISS 0
#define SNIPECODE_BRAINSTEM 1
#define SNIPECODE_HEART	2
#define SNIPECODE_CHEST 3
#define SNIPECODE_ABDOMEN 4
#define SNIPECODE_SHOULDER 5
#define SNIPECODE_ARM	6
#define SNIPECODE_LEG	7
#define SNIPECODE_CHEST_SCRAPE	8

#define SNIPEOCULAR_RELAXED	0
#define SNIPEOCULAR_TENSE	2
#define SNIPEOCULAR_TENSING		1
#define SNIPEOCULAR_TREMBLING	3
#define SNIPEOCULAR_BLURRING	4
#define SNIPEOCULAR_LOSINGFOCUS	5
#define SNIPEOCULAR_LOST		6
#define MAX_SNIPE_OCULAR_STATES	6

#define MAX_OCULAR_HOLD_SECONDS	90
#define MIN_OCULAR_HOLD_SECONDS	20

#define MIN_OCULAR_RECOVERY_SECONDS	15
#define MAX_OCULAR_RECOVERY_SECONDS 90

#define SNIPECHAR_UPARROW 30
#define SNIPECHAR_DNARROW 31
#define SNIPECHAR_LTARROW 16
#define SNIPECHAR_RTARROW 17
#define SNIPECHAR_CROSS 197
#define SNIPECHAR_HLINE 196

#define SNIPE_MAX_SLEEP	40
#define SNIPE_DROP_PER_OCULAR	5
#define SNIPE_SLEEP_CALMNESS_BONUS 3

//ENEMY DEFINES
#define ENEMY_STATUS_ALIVE			0
#define ENEMY_STATUS_UNCONSCIOUS	1
#define ENEMY_STATUS_DEAD			2

//MISSION DEFINES
#define PRIMARY_COMPLETE 1
#define PRIMARY_INCOMPLETE 0

//GRAPHICS DEFINES
#define CIS_GRAPHIC_ID 1
#define CIS_GRAPHIC_FILE "data\\cis.gfx"
#define SNIPE_GRAPHIC_ID 2
#define SNIPE_GRAPHIC_FILE "data\\scope.gfx"
#define CODESCREEN_GRAPHIC_ID 3
#define CODESCREEN_GRAPHIC_FILE "data\\codescr.gfx"
#define ATOMICSCREEN_GRAPHIC_ID 4
#define ATOMICSCREEN_GRAPHIC_FILE "data\\atomic.gfx"
#define PROMPT_GRAPHIC_ID 5
#define PROMPT_GRAPHIC_FILE "data\\prompt.gfx"
#define PROMPTRESPONSE_GRAPHIC_ID 6
#define PROMPTRESPONSE_GRAPHIC_FILE "data\\prmtbox.gfx"
#define MELEE_GRAPHIC_ID	7
#define MELEE_GRAPHIC_FILE	"data\\melee.gfx"
#define SARTU_GRAPHIC_ID	8
#define SARTU_GRAPHIC_FILE	"data\\sartu.gfx"
#define ARMORY_GRAPHIC_ID	9
#define ARMORY_GRAPHIC_FILE "data\\armory.gfx"
#define MAINUI_GRAPHIC_ID	10
#define MAINUI_GRAPHIC_FILE	"data\\mainui.gfx"
#define RADIO_GRAPHIC_ID	11
#define RADIO_GRAPHIC_FILE	"data\\radio.gfx"
#define SHOOTING_SILHOUETTE_CLEAR_ID	12
#define SHOOTING_SILHOUETTE_CLEAR_FILE	"data\\sil_clear.gfx"
#define SHOOTING_SILHOUETTE_FULLCOVER_ID	13
#define SHOOTING_SILHOUETTE_FULLCOVER_FILE	"data\\sil_fullcover.gfx"
#define SHOOTING_SILHOUETTE_PARTIALCOVER_ID	14
#define SHOOTING_SILHOUETTE_PARTIALCOVER_FILE	"data\\sil_partialcover.gfx"


//VEHICLE DEFINES
#define VEHICLE_CAR 0
#define VEHICLE_TRUCK 1
#define VEHICLE_VAN 2

#define MAX_VEHICLE_WHEELS 4

#define VEHICLE_RIGGED 1
#define VEHICLE_NOTRIGGED 0

#define VEHICLE_LEAKING 1
#define VEHICLE_NOTLEAKING 0

#define VEHICLE_GAS_OK 0
#define VEHICLE_GAS_SABOTAGED 1

#define VEHICLE_WINDOWBROKEN 0
#define VEHICLE_WINDOWNOTBROKEN 1

#define MAX_VEHICLE_WINDOWS 6
#define VEHICLE_WINDOW_FRONTWINDSHIELD 0
#define VEHICLE_WINDOW_DRIVERFRONT 1
#define VEHICLE_WINDOW_PASSENGERFRONT 2
#define VEHICLE_WINDOW_DRIVERBACK 3
#define VEHICLE_WINDOW_PASSENGERBACK 4
#define VEHICLE_WINDOW_REARWINDSHIELD 5

#define MAX_VEHICLE_BRAKELINES 4
#define VEHICLE_BRAKELINE_FRONTLEFT 0
#define VEHICLE_BRAKELINE_FRONTRIGHT 1
#define VEHICLE_BRAKELINE_BACKLEFT 2
#define VEHICLE_BRAKELINE_BACKRIGHT 3

//SOUND DEFINES
#define TYPEWRITER_SOUND "sounds\\common\\type.wav"
#define BEEPA_SOUND "sounds\\common\\type2.wav"
#define BEEPB_SOUND "sounds\\common\\type3.wav"
#define BEEPC_SOUND "sounds\\common\\type4.wav"
#define TWOBEEPS_SOUND "sounds\\common\\beep1.wav"
#define TWOBEEPSMOD_SOUND "sounds\\common\\beep2.wav"
#define SILENCER_SOUND "sounds\\modifiers\\silencer.wav"
#define FLASHSUPPRESSOR_SOUND "sounds\\modifiers\\flashsuppressor.wav"
#define LASERSIGHT_SOUND "sounds\\modifiers\\lasersight.wav"
#define ELEVATOR_SOUND	"sounds\\common\\elevator.wav"
#define BELLS_SOUND	"sounds\\common\\bells.wav"
#define WEAPON_SOUND_CLICK "sounds\\weapons\\click.wav"

#define TYPEWRITER 0
#define BEEPA	1
#define BEEPB	2
#define BEEPC	3
#define TWOBEEPS	4
#define TWOBEEPSMOD	5



//CODE SCREEN DEFINES
#define AC_TEXTBOXTOPLEFT_X	10
#define AC_TEXTBOXTOPLEFT_Y	17
#define AC_TEXTBOXBOTTOMRIGHT_X	69
#define AC_TEXTBOXBOTTOMRIGHT_Y	18
#define AC_INITIALNUMBERBLOCK_X 9
#define AC_INITIALNUMBERBLOCK_Y	4


//DOOR DEFINES
#define DOOR_GLASS	0
#define DOOR_WOOD	1
#define DOOR_METAL	2
#define DOOR_REMETAL	3

#define DOOR_LOCK_NONE	0
#define DOOR_LOCK_LIS	1
#define DOOR_LOCK_CIS	2

#define DOOR_NOALARM	0
#define DOOR_ALARM	1

#define DOOR_KEYCARD	1
#define DOOR_NOKEYCARD	0
#define DOOR_KEYCARD_TAU		1
#define DOOR_KEYCARD_THETA		2
#define DOOR_KEYCARD_OMICRON	4
#define DOOR_KEYCARD_EPSILON	8
#define DOOR_KEYCARD_PHI		16
#define DOOR_KEYCARD_RHO		32
#define MAX_DOOR_KEYCARDS		6
#define MAX_KEYCARD_DUPLICATES	5
#define DOOR_KEYCARD_ACTIVE_SOUND	"sounds\\common\\keycardwork.wav"

#define DOOR_OPEN_SOUND			"sounds\\common\\door.wav"
#define DOOR_CLOSE_SOUND		"sounds\\common\\doorclose.wav"

//TITLE SCREEN DEFINES
#define	TS_OPCON	0
#define	TS_PERSONNEL	1
#define	TS_ARMORY	2
#define TS_TRAINING	3
#define	TS_SARTU	4
#define	TS_SILENTWALL	5
#define TS_NUCLEAR 6
#define TS_FINAL	7

//MELEE COMBAT DEFINES
#define MELEE_ENEMYDEAD	2
#define MELEE_ENEMYUNCONSCIOUS	1
#define MELEE_PLAYERDEAD	-1
#define MELEE_CONTINUE	0

//CIS DEFINES
#define CIS_MAX_SPECIAL_DIGITS 4
#define CIS_MAX_STRING_VELOCITY 4
#define CIS_VELOCITY_LEFT FALSE
#define CIS_VELOCITY_RIGHT TRUE
#define CIS_MAX_DISPLAYABLE_DIGITS 40
#define CIS_MAX_SYNCHRONIZE_TIME 120
#define CIS_GRAPHIC_OFFSET_Y_FROM_TOP 7
#define CIS_GRAPHIC_OFFSET_X_FROM_LEFT 18
#define CIS_TSTRING_OFFSET_Y_FROM_TOP 1
#define CIS_TSTRING_OFFSET_X_FROM_LEFT 2
#define CIS_PSTRING_OFFSET_Y_FROM_TOP 3
#define CIS_PSTRING_OFFSET_X_FROM_LEFT 2
#define CIS_STATUS_OFFSET_Y_FROM_TOP 7
#define CIS_STATUS_OFFSET_X_FROM_LEFT 2
#define CIS_NUMBER_OF_STATUS_MESSAGES 4
#define CIS_STATUS_MESSAGE_AWAITING 0
#define CIS_STATUS_MESSAGE_SYNCHRONIZING 1
#define CIS_STATUS_MESSAGE_FAILURE 2
#define CIS_STATUS_MESSAGE_SUCCESS 3
#define CIS_STATUS_MESSAGEFADE_FADEIN 0
#define CIS_STATUS_MESSAGEFADE_HOLD 1
#define CIS_STATUS_MESSAGEFADE_FADEOUT 2
#define CIS_STATUS_MESSAGEFADE_NONE 3

//ATOMIC DEFINES
#define ATOMIC_RECIEVE_SOUND	"sounds\\common\\atomic.wav"
#define ATOMIC_ACTIVATE_SOUND	"sounds\\gizmos\\nukeactive.wav"
#define ATOMIC_PRIME_SOUND		"sounds\\gizmos\\nukeprimed.wav"
#define ATOMIC_SAFE_SOUND		"sounds\\gizmos\\nukesafe.wav"

#define ATOMIC_DEVICE_Y_OFFSET 7
#define ATOMIC_DEVICE_X_OFFSET 20
#define ATOMIC_CODE_Y_OFFSET 10
#define ATOMIC_CODE_X_OFFSET 20
#define ATOMIC_MESSAGES_LENGTH 20
#define ATOMIC_MESSAGES_X_OFFSET 25
#define ATOMIC_MESSAGES_Y_OFFSET 5
#define ATOMIC_LIGHT_WIDTH 2
#define ATOMIC_LIGHT_HEIGHT 1
#define ATOMIC_LIGHTRACK_X_OFFSET 3
#define ATOMIC_LIGHTRACK_Y_OFFSET 1
#define ATOMIC_SINGLELIGHT1_X_OFFSET 40
#define ATOMIC_SINGLELIGHT1_Y_OFFSET 2
#define ATOMIC_SINGLELIGHT2_X_OFFSET 42
#define ATOMIC_SINGLELIGHT2_Y_OFFSET 9
//LIGHT STATUS
#define ATOMIC_LIGHT_OFF 0
#define ATOMIC_LIGHT_DIMUP 1
#define ATOMIC_LIGHT_BRIGHT 2
#define ATOMIC_LIGHT_DIMDOWN 3
//LIGHT TYPES
#define ATOMIC_LIGHT_FLASH 0
#define ATOMIC_LIGHT_FADE 1
#define MAX_ATOMIC_CODE_DIGITS 10
#define BLOCK_CHARACTER 219

//PROMPT DEFINES
#define PROMPTANSWER_YESNO 0
#define PROMPTANSWER_NUMBER 1
#define PROMPTANSWER_STRING 2
#define PROMPTANSWER_ANYKEY 3
#define PROMPT_TEXT_SPACE_X_OFFSETFROMLEFT 16
#define PROMPT_TEXT_SPACE_Y_OFFSETFROMTOP 4
#define PROMPT_TEXT_WIDTH	46
#define PROMPT_TEXT_HEIGHT 15

//BODY DIAGRAM
#define BODY_HEAD		7
#define BODY_LSHOULDER	8
#define BODY_RSHOULDER	6
#define BODY_TORSO		4
#define BODY_RSIDE		3
#define BODY_LSIDE		5
#define BODY_ABDOMEN	1
#define BODY_LLEG		2
#define BODY_RLEG		0

#define MAX_BODY_PARTS	9

//WOUND BITFIELD FOR BODY DIAGRAM
#define WOUND_CUT			1
#define WOUND_SHOT			2
#define WOUND_BLUNT			4
#define WOUND_LACERATION	8
#define WOUND_BLOWNTOSHREDS	16
#define WOUND_BONEBROKEN	32

//GIZMOS!!!
#define GIZMO_TYPE_NONE			0
#define GIZMO_TYPE_BUG			1
#define GIZMO_TYPE_SPIKEMIKE	2
#define GIZMO_TYPE_NVG			3
#define GIZMO_TYPE_TAS			4
#define GIZMO_TYPE_XRIFLE		5
#define GIZMO_TYPE_FOVS			6
#define GIZMO_TYPE_LIS			7
#define GIZMO_TYPE_CIS			8
#define GIZMO_TYPE_SBK			9
#define GIZMO_TYPE_LENSES		10
#define GIZMO_TYPE_RING			11
#define GIZMO_TYPE_WATCH		12
#define GIZMO_TYPE_LEGPACKS			13
#define GIZMO_TYPE_BINOCULARS	14
#define GIZMO_TYPE_C4TIMED		15
#define GIZMO_TYPE_C4SWITCH	16
#define GIZMO_TYPE_C4PROXIMITY	17
#define GIZMO_TYPE_C4ELECTRONIC	18
#define GIZMO_TYPE_OCTYLDICHLORIDE	19
#define GIZMO_TYPE_GASMASK					20
#define GIZMO_TYPE_TRAUMAPLATES				21
#define MAX_GIZMOS				21

#define TRAUMAPLATE_HIT_SOUND	"sounds\\gizmos\\traumaplate.wav"

#define REMOTE_C4_RADIO_CHOICES 3
#define ELECTRONIC_C4_VOLTAGE_CHOICES 2
#define TIMED_C4_MINUTE_CHOICES 5
#define PROXIMITY_C4_RANGE_CHOICES	5

#define REMOTE_C4_FREQUENCY_NONE	0
#define REMOTE_C4_FREQUENCY_900GHZ	1
#define	REMOTE_C4_FREQUENCY_1200GHZ	2
#define REMOTE_C4_FREQUENCY_1500GHZ	3

#define ELECTRONIC_C4_VOLTAGE_NONE	0
#define ELECTRONIC_C4_VOLTAGE_15V	1
#define ELECTRONIC_C4_VOLTAGE_110V	2

#define PROXIMITY_C4_RANGE_NONE		0
#define PROXIMITY_C4_RANGE_5FT		1
#define PROXIMITY_C4_RANGE_10FT		2
#define PROXIMITY_C4_RANGE_15FT		3
#define PROXIMITY_C4_RANGE_20FT		4
#define PROXIMITY_C4_RANGE_25FT		5

#define TIMED_C4_MINUTES_NONE		0
#define TIMED_C4_MINUTES_1MIN		1
#define TIMED_C4_MINUTES_5MIN		2
#define TIMED_C4_MINUTES_20MIN		3
#define TIMED_C4_MINUTES_60MIN		4
#define TIMED_C4_MINUTES_90MIN		5

#define C4_PROXIMITY_ARM					"sounds\\gizmos\\nukeprimed.wav"
#define C4_PROXIMITY_YOURESCREWED			"sounds\\gizmos\\nvon.wav"

#define C4_TYPE_SELECT_SOUND				"sounds\\common\\weaponselect.wav"
#define C4_ARM_SOUND						"sounds\\gizmos\\bombarm.wav"

#define XRIFLE_ON_SOUND						"sounds\\gizmos\\xrifleon.wav"
#define XRIFLE_OFF_SOUND					"sounds\\gizmos\\xrifleoff.wav"

#define NVG_ON_SOUND						"sounds\\gizmos\\nvon.wav"
#define NVG_OFF_SOUND					"sounds\\gizmos\\nvoff.wav"

#define THERM_ON_SOUND						"sounds\\gizmos\\thermon.wav"
#define THERM_OFF_SOUND					"sounds\\gizmos\\thermoff.wav"

#define GASMASK_ON_SOUND					"sounds\\common\\pickupweapon.wav"
#define GASMASK_OFF_SOUND					"sounds\\common\\pickupweapon.wav"

#define BINOCULARS_ON_SOUND					"sounds\\common\\pickupweapon.wav"
#define BINOCULARS_OFF_SOUND					"sounds\\common\\pickupweapon.wav"

#define SPIKEMIKE_ON_SOUND					"sounds\\common\\pickupweapon.wav"
#define SPIKEMIKE_OFF_SOUND					"sounds\\common\\pickupweapon.wav"

#define SCOPE_ZOOM_SOUND					"sounds\\gizmos\\scopeclick.wav"
#define ELECTRONIC_ZOOM_SOUND				"sounds\\gizmos\\zoom.wav"
#define XRIFLE_ZOOM_SOUND					"sounds\\gizmos\\xriflezoom.wav"

#define GIZMO_DROP_SOUND					"sounds\\weapons\\gundrop.wav"

#define GRENADE_PRIME_SOUND					"sounds\\gizmos\\grenadepin.wav"
#define GRENADE_BOUNCE_SOUND				"sounds\\gizmos\\grenadebounce.wav"

#define GRENADE_EXPLODE_FRAG				"sounds\\gizmos\\fraggrenade.wav"
#define GRENADE_EXPLODE_FLASH				"sounds\\gizmos\\flashgrenade.wav"
#define GRENADE_EXPLODE_SMOKE				"sounds\\gizmos\\smokegrenade.wav"
#define GRENADE_EXPLODE_TOXIN				"sounds\\gizmos\\toxingrenade.wav"

#define WEAPONSCOPE_ZOOM_MAX	8.0
#define BINOCULARS_ZOOM_MAX	6.0
#define TAS_ZOOM_MAX	6.0
#define NVG_ZOOM_MAX	4.0
#define HUMAN_ZOOM_MAX	2.0
#define GASMASK_ZOOM_MAX	1.5
#define SPIKEMIKE_ZOOM_MAX	4.0
#define MAX_CIS_ENCRYPTIONSTRENGTH	9
#define MIN_CIS_ENCRYPTIONSTRENGTH	3
#define MAX_LIS_RINGS				6
#define MIN_LIS_RINGS				3

//GRENADES
#define GRENADE_TYPE_NONE		0
#define GRENADE_FRAG			1
#define GRENADE_FLASH			2
#define GRENADE_SMOKE			3
#define GRENADE_TOXIN			4
#define MAX_GRENADES			4

//HONOR BOARD
#define HB_MISSION_SORTING	0
#define HB_KILL_SORTING	1
#define HB_DAMAGE_SORTING	2

//PREFAB PLACEMENT
#define PREFAB_PLACED_FAILURE_LOCKEDOUT	1
#define PREFAB_PLACED_OK	0
#define PREFAB_PLACED_FAILURE_OUTOFBOUNDS	-1
#define PREFAB_PLACED_FAILURE_NULLCELL	-2

#define PREFAB_FILL_FAILURE_NULLCELL -1
#define PREFAB_FILL_OK									0

//MAIN UI DEFINES
#define MAINUI_MAPBOXXORIGIN		1
#define MAINUI_MAPBOXYORIGIN		1
#define MAINUI_MAPBOXWIDTH			38
#define MAINUI_MAPBOXHEIGHT			11
#define MAINUI_STATUSBOXXORIGIN		40
#define MAINUI_STATUSBOXYORIGIN		1
#define MAINUI_STATUSBOXWIDTH		38
#define MAINUI_STATUSBOXHEIGHT		9
#define MAINUI_TIMEBOXXORIGIN		40
#define MAINUI_TIMEBOXYORIGIN		12
#define MAINUI_TIMEBOXWIDTH			38
#define MAINUI_TIMEBOXHEIGHT		0
#define MAINUI_HISTORYBOXXORIGIN	1
#define MAINUI_HISTORYBOXYORIGIN	14
#define MAINUI_HISTORYBOXHEIGHT		8
#define MAINUI_HISTORYBOXWIDTH		77
#define MAINUI_VIEWPORT_SHORTDISTANCE	7
#define MAINUI_VIEWPORT_LONGDISTANCE	15

//DIRECTION DEFINES
#define TURN_DIRECTION_NORTH	0
#define TURN_DIRECTION_SOUTH	1
#define TURN_DIRECTION_EAST		2
#define TURN_DIRECTION_WEST		3
#define MAX_TURN_DIRECTIONS		4

//ENVIRON DEFINES
#define ENVIRON_TYPE_SMOKE		1
#define ENVIRON_TYPE_TOXIN		2
#define ENVIRON_TYPE_FIRE		3
#define ENVIRON_TYPE_ALL		-1

//ACTION DEFINES
#define ACTION_MODE_MOVE		0
#define ACTION_MODE_TURN		1
#define ACTION_MODE_ZOOM		2
#define ACTION_MODE_SHOOT		3
#define ACTION_MODE_ZOOMSHOOT	4
#define ACTION_MODE_USE			5
#define ACTION_MODE_THROW		6

//SURGERY TYPES
#define SURGERY_TYPE_BROKENARM	0
#define SURGERY_TYPE_VERTEBRAEFRAG	1
#define SURGERY_TYPE_ORGANDAMAGE	2
#define SURGERY_TYPE_NERVEDAMAGE	3
#define SURGERY_TYPE_NERVESHREDDING	4
#define SURGERY_TYPE_OCULARDAMAGE	5
#define SURGERY_TYPE_TORNHANDTENDONS	6
#define SURGERY_TYPE_TORNHANDLIGAMENTS	7
#define SURGERY_TYPE_NEGATIVEBRAINPATTERNS	-1
#define MAX_SURGERY_TYPES	8


#define MISSION_RESULT_REACHEDRZPRIMARYSUCCESS	0
#define MISSION_RESULT_REACHEDRZPRIMARYFAILURE	1
#define MISSION_RESULT_ESCAPERETURNPRIMARYSUCCESS	2
#define MISSION_RESULT_ESCAPERETURNPRIMARYFAILURE	3
#define MISSION_RESULT_ESCAPENORETURNPRIMARYSUCCESS	4
#define MISSION_RESULT_ESCAPENORETURNRETURNPRIMARYFAILURE	5
#define MISSION_RESULT_CAPTUREDPRIMARYSUCCESS	6
#define MISSION_RESULT_CAPTUREDPRIMARYFAILURE	7
#define MISSION_RESULT_CYANIDEDPRIMARYSUCCESS	8
#define MISSION_RESULT_CYANIDEDPRIMARYFAILURE	9
#define MISSION_RESULT_ESCAPEDTORTURE			10
#define MISSION_RESULT_CHECKPLAYERSTATUS		11

#define MAP_ARMORY_TYPE_DEPLOYMENT			0
#define MAP_ARMORY_TYPE_EMERGENCY			1
#define MAP_ARMORY_TYPE_STORAGE				2
#define MAP_ARMORY_TYPE_AMMUNITION			3
#define MAP_ARMORY_TYPE_NONE				4
#define MAX_MAP_ARMORY_TYPES				5
#define MAX_MAP_ARMORY_ITEMS				10
#define MAP_ARMORY_OPEN_SOUND				"sounds\\common\\locker.wav"
#define MAP_ARMORY_CLOSE_SOUND				"sounds\\common\\lockerclose.wav"

///SCRIPTED SEQUENCES
#define SCRIPTEDEVENT_TYPE_DOORCLOSE				1
#define SCRIPTEDEVENT_TYPE_OCULARFOCUS				2
#define SCRIPTEDEVENT_TYPE_ENEMYREGAINCONSCIOUSNESS	3
#define SCRIPTEDEVENT_TYPE_ENEMYSTANDUP				4
#define SCRIPTEDEVENT_TYPE_DRUGWEAROFF				5
#define SCRIPTEDEVENT_TYPE_REMEDK					6
#define SCRIPTEDEVENT_TYPE_ANTIDOTEWEAROFF			7
#define SCRIPTEDEVENT_TYPE_PROXBOMBACTIVATE			8
#define SCRIPTEDEVENT_TYPE_TIMEDBOMBEXPLODE			9
#define SCRIPTEDEVENT_TYPE_AMPLIFIEDTRACKING		10
#define SCRIPTEDEVENT_TYPE_NROSCAN					11
#define SCRIPTEDEVENT_TYPE_IMMEDIATEPICKUPREQUEST	12
#define SCRIPTEDEVENT_TYPE_TIMETOPICKUPREQUEST		13
#define SCRIPTEDEVENT_TYPE_REMOTEBOMBDETONATE		14
#define SCRIPTEDEVENT_TYPE_GRENADEDETONATE			15

//INVENTORY DEFINES
#define INVENTORY_MAIN_POPUP_SOUND				"sounds\\common\\weaponselect.wav"

#define ACTIVATEDEACTIVATE_WEAPON_SOUND			"sounds\\common\\pickupweapon.wav"

#define DUMP_GENERIC_AMMO_SOUND					"sounds\\weapons\\dumpammo.wav"
#define DUMP_BULLET_SOUND						"sounds\\weapons\\dumpbullet.wav"
#define DUMP_SHELL_SOUND						"sounds\\weapons\\dumpshell.wav"
#define DUMP_EXPLOSIVE_SOUND					"sounds\\weapons\\dumpexplosive.wav"

#define CYLINDER_LOAD_SPINCHAMBER_SOUND			"sounds\\weapons\\cylinderspin.wav"
#define CYLINDER_LOAD_OPENCHAMBER_SOUND			"sounds\\weapons\\cylinderopen.wav"
#define CYLINDER_LOAD_CLOSECHAMBER_SOUND		"sounds\\weapons\\cylinderclose.wav"
#define CYLINDER_LOAD_CHANGECHAMBER_SOUND		"sounds\\weapons\\cylinderclick.wav"

#define CLIP_OUT_SAVE_SOUND						"sounds\\weapons\\clipout.wav"
#define CLIP_OUT_DUMP_SOUND						"sounds\\weapons\\clipoutdump.wav"
#define CLIP_DUMP_SOUND							"sounds\\weapons\\gundrop.wav"

#define LOAD_INSERTSHELL_SOUND					"sounds\\weapons\\shellinsert.wav"
#define LOAD_INSERTBULLET_SOUND					"sounds\\weapons\\bulletinsert.wav"
#define LOAD_FILLSHELL_SOUND					"sounds\\weapons\\magazinefill.wav"
#define LOAD_FILLBULLET_SOUND					"sounds\\weapons\\bulletfill.wav"
#define LOAD_SPEEDLOAD_SOUND					"sounds\\weapons\\speedloader.wav"

//ENEMY ALERT DEFINES
#define ENEMY_ALERT_WHITE	0
#define ENEMY_ALERT_YELLOW	1
#define ENEMY_ALERT_ORANGE	2
#define ENEMY_ALERT_RED		3
#define ENEMY_ALERT_BLACK	4

//RADIO DEFINES
#define RADIO_TRANSMISSION_PAUSE_TIME 50
#define RADIO_MAX_SQUELCH_CHANNELS	20
#define RADIO_TRANSMISSION_SIGNAL_LOSS_TIME	400
#define RADIO_MAX_FREQHOP_TIME	800
#define RADIO_MIN_FREQHOP_TIME	450
#define RADIO_STATUSLINE_YORIGIN	20
#define RADIO_SNR_XORIGIN	5
#define RADIO_SNR_WIDTH		4
#define RADIO_STATUS_XORIGIN	26
#define RADIO_STATUS_WIDTH		33
#define RADIO_SQUELCH_XORIGIN	74
#define RADIO_SQUELCH_WIDTH	4
#define RADIO_WORDS_HEIGHT			17
#define RADIO_WORDS_WIDTH			76
#define RADIO_TRANSMISSIONLOST_SNR	20
#define RADIO_SLEEP	40
#define RADIO_MAX_CHANNELS	5
#define RADIO_ON_SOUND	"sounds\\gizmos\\radioon.wav"
#define RADIO_OFF_SOUND	"sounds\\gizmos\\bombarm.wav"
#define RADIO_SWITCHCHANNEL_SOUND	"sounds\\common\\weaponselect.wav"
#define RADIO_STATIC_SOUND	"sounds\\gizmos\\radiostatic.wav"
#define RADIO_OPENCHANNEL_SOUND	"sounds\\gizmos\\radioopen.wav"
#define RADIO_DETONATE_SOUND	"sounds\\gizmos\\nvon.wav"

#define RAYCAST_BLOCK_NONE			0
#define RAYCAST_BLOCK_WALL			1
#define RAYCAST_BLOCK_CORNER		2
#define RAYCAST_BLOCK_DOOR			3
#define RAYCAST_BLOCK_LOOBS			4
#define RAYCAST_BLOCK_HIOBS			5
#define RAYCAST_BLOCK_VEHICLE		6
#define RAYCAST_BLOCK_HUMAN			7
#define RAYCAST_BLOCK_OUTOFBOUNDS	8

#define RAYCAST_OBJECT_BUILDINGS	0
#define RAYCAST_OBJECT_HIOBS		1
#define RAYCAST_OBJECT_LOOBS		2
#define RAYCAST_OBJECT_VEHICLES		3
#define RAYCAST_OBJECT_LIVEHUMANS	4
#define RAYCAST_OBJECT_DEADHUMANS	5
#define RAYCAST_OBJECT_GIZMOS		6
#define RAYCAST_OBJECT_ITEMS		7

#define RAYCAST_HIOBS_RANGERATIO	.90
#define RAYCAST_LOOBS_RANGERATIO	.85
#define RAYCAST_VEHICLES_RANGERATIO .70
#define RAYCAST_LIVEHUMANS_RANGERATIO	.50
#define RAYCAST_DEADHUMANS_RANGERATIO	.45
#define RAYCAST_GIZMOS_RANGERATIO		.35
#define RAYCAST_ITEMS_RANGERATIO		.30

#define RAYCAST_TAS_BONUS_LIVEHUMANS	.10
#define RAYCAST_TAS_BONUS_VEHICLES		.05

#define RAYCAST_NVG_BONUS_ITEMS			.10
#define RAYCAST_NVG_BONUS_GIZMOS		.15

#define AI_DEFAULT_BEHAVIOR_PATROL		0
#define	AI_DEFAULT_BEHAVIOR_GUARD		1
#define AI_DEFAULT_BEHAVIOR_HUNT		2
#define AI_DEFAULT_BEHAVIOR_FENCE		3
#define AI_DEFAULT_BEHAVIOR_ESCORT		4
#define AI_DEFAULT_BEHAVIOR_PRIMARY		5