#include "xaudio\\xaudio.h"
#include "xaudio\\audio_output.h"
#include "xaudio\\control.h"
#include "xaudio\\control_win32.h"
#include "xaudio\\player.h"
#include "xaudio\\decoder.h"
#include "xaudio\\file_input.h"
#include "xaudio\\file_output.h"
#include "xaudio\\memory_input.h"
#include "xaudio\\stream_input.h"

//#include "xaudio\\xanalyze.h"