//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WeaponEditor.rc
//
#define MAINMENUDIALOG                  101
#define WEAPONDIALOG                    102
#define MAINAMMODIALOG                  108
#define SHELLDIALOG                     109
#define EXPLOSIVEDIALOG                 110
#define BULLETDIALOG                    111
#define IDB_BITMAP1                     112
#define EDITORICON                      116
#define CHOOSEAMMOED_BUTTON             1000
#define CHOOSEWEAPONED_BUTTON           1001
#define IDQUIT                          1002
#define IDQUITSAVE                      1003
#define IDQUITNOSAVE                    1004
#define FILINGTYPEBOX                   1007
#define CLASSTYPEBOX                    1008
#define CLEARBUTTON                     1009
#define LONGNAMEBOX                     1010
#define SHORTNAMEBOX                    1011
#define DSAONLYCHECK                    1012
#define AMMOLOADTYPEBOX                 1013
#define DESCBOX                         1017
#define FREQUENCYBOX                    1018
#define FREQUENCYSPIN                   1026
#define BASEACCURACYBOX                 1027
#define BASEACCURACYSPIN                1028
#define ROUNDSPERTURNBOX                1029
#define ROUNDSPERTURNSPINNER            1030
#define SUBMITNEWBUTTON                 1031
#define TOTALWEAPONSBOX                 1032
#define CURRENTWEAPONBOX                1033
#define SUBMITMODIFIEDBUTTON            1034
#define WEAPONLOADBOX                   1035
#define REMOVEBUTTON                    1035
#define FLASHLEVELBOX                   1036
#define FLASHLEVELSPIN                  1037
#define SOUNDLEVELBOX                   1038
#define SOUNDLEVELSPIN                  1039
#define WEAPONACTIONCHECKSHOOT          1041
#define WEAPONACTIONCHECKHIT            1042
#define WEAPONACTIONCHECKCUT            1043
#define WEAPONACTIONCHECKTHROW          1044
#define WEAPONACTIONCHECKDRUG           1045
#define WEAPONACTIONCHECKSNIPE          1046
#define MAINAMMOBOX                     1047
#define MODIFIERCHECKLASERSIGHT         1048
#define MODIFIERCHECKFLASHSUPPRESSOR    1049
#define MODIFIERCHECKSILENCER           1050
#define WEIGHTONESBOX                   1051
#define WEIGHTTENTHSBOX                 1052
#define DRUGTYPEBOX                     1053
#define DRUGDOSESBOX                    1054
#define MAXAMMOBOX                      1055
#define CURRENTAMMOBOX                  1056
#define REMOVEBUTTON2                   1056
#define TOTALAMMOBOX                    1057
#define ROUNDSPERTURNSPINNER2           1057
#define SUBAMMOTYPESBOX                 1058
#define ROUNDSPERTURNSPINNER3           1058
#define SUBAMMOTYPE                     1061
#define MAINAMMOTYPEBOX                 1062
#define AMMONAME                        1064
#define SHELLEDITCOMBOBOX               1066
#define EDITSUBAMMOBUTTON               1067
#define SHELLSHORTNAME                  1070
#define SHELLCHECKDSAONLY               1071
#define SHELLLONGNAME                   1072
#define SHELLDESCBOX                    1073
#define SHELLFREQUENCYBOX               1074
#define SHELLFREQUENCYSPIN              1075
#define SHELLSPREADBOX                  1076
#define SHELLSPREADSPIN                 1077
#define SHELLAPBOX                      1078
#define SHELLAPSPIN                     1079
#define SHELLENERGYBOX                  1080
#define SHELLENERGYSPIN                 1081
#define SHELLDAMAGEBOX                  1082
#define SHELLDAMAGESPIN                 1083
#define SHELLSOUNDBOX                   1084
#define MAINAMMONAME                    1085
#define BULLETLATENTDAMAGEBOX           1086
#define LATENTDAMAGESPIN                1087
#define EXPLOSIVEDELAYBOX               1088
#define RANGESPIN                       1089
#define EXPLOSIVERANGEBOX               1090
#define EXRANGESPIN                     1091
#define EXPLOSIVEINITRADIUSBOX          1092
#define EXPLOSIVEINITSTRENGTHBOX        1093
#define SHELLDAMAGESPIN2                1094
#define EXPLOSIVEINITTYPEBOX            1095
#define EXPLOSIVELATENTTIMEBOX          1096
#define LATENTTIMESPIN                  1097
#define EXPLOSIVELATENTRADIUSBOX        1098
#define LATENTRADIUSSPIN                1099
#define EXPLOSIVELATENTTYPEBOX          1100
#define EXPLOSIVEFREQUENCYBOX           1101
#define EXPLOSIVELONGNAME               1102
#define EXPLOSIVESHORTNAME              1103
#define EXPLOSIVEEDITCOMBOBOX           1104
#define EXPLOSIVEDESCBOX                1105
#define EXPLOSIVESOUNDBOX               1106
#define CLEARFIELDSBUTTON               1107
#define BULLETEDITCOMBOBOX              1108
#define BULLETSHORTNAME                 1109
#define BULLETLONGNAME                  1110
#define BULLETDESCBOX                   1111
#define BULLETCHECKDSAONLY              1112
#define BULLETFREQUENCYBOX              1113
#define BULLETAPBOX                     1114
#define BULLETENERGYBOX                 1115
#define BULLETDAMAGEBOX                 1116
#define BULLETSOUNDBOX                  1117
#define EXPLOSIVECHECKDSAONLY           1118
#define FIRESOUNDBOX                    1119
#define HITSOUNDBOX                     1120
#define THROWSOUNDBOX                   1121
#define DROPSOUNDBOX                    1123
#define RELOADSOUNDBOX                  1124
#define BREAKSOUNDBOX                   1125
#define MAINMENUBOTTOMCAPTION           -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
